apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-blog-wp-cron
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: my-blog-wp-config
            configMap:
              name: my-blog-wp-config
          containers:
          - name: wp-cron
            image: asia.gcr.io/vinta-254817/my-blog:79b0996
            command: ["/usr/local/bin/php"]
            args:
            - /usr/src/wordpress/wp-cron.php
            volumeMounts:
            - name: my-blog-wp-config
              mountPath: /usr/src/wordpress/wp-config.php
              subPath: wp-config.php
              readOnly: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: code-blog-wp-cron
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: code-blog-wp-config
            configMap:
              name: code-blog-wp-config
          containers:
          - name: wp-cron
            image: asia.gcr.io/vinta-254817/code-blog:79b0996
            command: ["/usr/local/bin/php"]
            args:
            - /usr/src/wordpress/wp-cron.php
            volumeMounts:
            - name: code-blog-wp-config
              mountPath: /usr/src/wordpress/wp-config.php
              subPath: wp-config.php
              readOnly: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
          restartPolicy: OnFailure
